
name: Main CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

#  deploy:
#    uses: ./.github/workflows/deploy.yml

  release:
    uses: ./.github/workflows/release.yml