on:
  workflow_call:

jobs:
  release:
    name: Publish the release (if any) with Nyx
    runs-on: ubuntu-latest
    steps:

    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Nyx publish
      id: nyx
      uses: mooltiverse/nyx@main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NYX_VERBOSITY: 'INFO'
      with:
        command: 'publish'
        changelogPath: 'CHANGELOG.md'
        preset: 'extended'
        releasePrefix: 'v'
        releaseLenient: 'true'
        stateFile: '.nyx-state.json'
        summaryFile: '.nyx-summary.txt'
        releaseTypesPublicationServices: 'github'
    outputs:
      current_tag: ${{ steps.nyx.outputs.version }}

  post-release:
    name: Post-release steps
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}/health-calculator
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ needs.release.outputs.current_tag }}
          dockerfile: ./health-calculator-service/Dockerfile
          context: './health-calculator-service'
