on:
  workflow_call:

jobs:
  release:
    name: Publish the release (if any) with Nyx
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
<<<<<<< Updated upstream

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Nyx infer
      id: nyx
      uses: mooltiverse/nyx@main

    - name: Print version # This step uses the version inferred by Nyx
      run: echo the inferred version is ${{ steps.nyx.outputs.version }}

    - name: Nyx mark
      uses: mooltiverse/nyx@main
      with:
        command: 'make'
        changelogPath: 'CHANGELOG.md'
        releasePrefix: 'v'
        preset: extended

    - name: Nyx mark
      uses: mooltiverse/nyx@main
      with:
        command: 'mark'
        changelogPath: 'CHANGELOG.md'
        releasePrefix: 'v'
        preset: extended

    - name: Nyx publish
      uses: mooltiverse/nyx@main
=======
    - name: Nyx publish
      id: nyx
      uses: mooltiverse/nyx@main
>>>>>>> Stashed changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NYX_VERBOSITY: 'INFO'
      with:
        command: 'publish'
        changelogPath: 'CHANGELOG.md'
<<<<<<< Updated upstream
        releasePrefix: 'v'
        preset: extended
        releaseTypesPublicationServices: 'GITHUB'
=======
        preset: 'extended'
        releaseLenient: 'true'
        stateFile: '.nyx-state.json'
        summaryFile: '.nyx-summary.txt'
>>>>>>> Stashed changes
